version: "3"

services:
  db:
    container_name: email-db
    image: bitnami/postgresql
    restart: always
    ports:
      - "5440:5432"
    environment:
        - POSTGRESQL_USERNAME=weslin
        - POSTGRESQL_PASSWORD=weslin
        - POSTGRESQL_DATABASE=emaildatabase