spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5440/springbootdb
    username: postgresql
    password: desafio

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: wesleeylirac12@gmail.com
    password: nrryuvgijykjmjqx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    addresses: amqps://******:NdHi8c6sw-XpYT-L5APgHT3YPi2iUpCB@sparrow.rmq.cloudamqp.com/murwkxya
    template:
      default-receive-queue: ms.project